### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zscmmm** [halo-sigs/plugin-unsplash#11]
1. 建议支持选择unsplash图片后，可以转存到附件中, 或OOS，返回自有连接.

2. 如果要使用Unsplash 的链接, 建议给出几个 url 参数选项按钮, 可以默认某些参数,进行 url 拼接, 毕竟返回原始图片太大了,  可以根据参数选择适当的图片大小, 这是有利于网络加速

3. 再文章写作中, 也可以使用 Unsplash

**Comment by ixianhao** [comment]
关注一下
